"""
Storage Package
数据存储层
"""
from app.storage.models import (
    Base,
    User,
    PreferenceRecord,
    Session,
    Message,
    AgentExecution,
    POI,
    POIRelationship,
    Restaurant,
    Itinerary,
    ItineraryPOI,
    Feedback,
    OperationLog,
    CacheEntry,
    MODELS,
    CREATE_ORDER,
)
from app.storage.database import (
    AsyncSessionLocal,
    SyncSessionLocal,
    get_db,
    get_db_context,
    init_db,
    drop_db,
    close_db,
)
from app.storage.repositories import (
    UserRepository,
    SessionRepository,
    MessageRepository,
    POIRepository,
    RestaurantRepository,
    ItineraryRepository,
    FeedbackRepository,
    OperationLogRepository,
    CacheRepository,
    AgentExecutionRepository,
    get_user_repository,
    get_session_repository,
    get_message_repository,
    get_poi_repository,
    get_restaurant_repository,
    get_itinerary_repository,
    get_feedback_repository,
    get_operation_log_repository,
    get_cache_repository,
    get_agent_execution_repository,
)
from app.storage.cache_manager import (
    RedisCacheManager,
    RedisSessionStore,
    get_cache_manager,
    get_session_store,
    init_redis,
    close_redis,
)
from app.storage.cache_strategy import (
    CacheStrategy,
    NoCache,
    MemoryCache,
    WriteThrough,
    WriteBehind,
    CacheAside,
    POICacheService,
    WeatherCacheService,
    SessionCacheService,
    LLMCacheService,
    RouteCacheService,
    CacheStats,
    cached,
    cache_invalidate,
)
from app.storage.vector_store import (
    BaseVectorStore,
    QdrantStore,
    InMemoryVectorStore,
    SearchResult,
    get_vector_store,
    init_vector_store,
    get_store,
)
from app.storage.vector_service import (
    VectorSearchService,
    POIEmbedding,
    EmbeddingGenerator,
    SearchResult as VSSearchResult,
    get_vector_service,
    get_embedding_generator,
    init_vector_service,
)

__all__ = [
    # Models
    "Base",
    "User",
    "PreferenceRecord",
    "Session",
    "Message",
    "AgentExecution",
    "POI",
    "POIRelationship",
    "Restaurant",
    "Itinerary",
    "ItineraryPOI",
    "Feedback",
    "OperationLog",
    "CacheEntry",
    "MODELS",
    "CREATE_ORDER",
    # Database
    "AsyncSessionLocal",
    "SyncSessionLocal",
    "get_db",
    "get_db_context",
    "init_db",
    "drop_db",
    "close_db",
    # Repositories
    "UserRepository",
    "SessionRepository",
    "MessageRepository",
    "POIRepository",
    "RestaurantRepository",
    "ItineraryRepository",
    "FeedbackRepository",
    "OperationLogRepository",
    "CacheRepository",
    "AgentExecutionRepository",
    "get_user_repository",
    "get_session_repository",
    "get_message_repository",
    "get_poi_repository",
    "get_restaurant_repository",
    "get_itinerary_repository",
    "get_feedback_repository",
    "get_operation_log_repository",
    "get_cache_repository",
    "get_agent_execution_repository",
    # Cache
    "RedisCacheManager",
    "RedisSessionStore",
    "get_cache_manager",
    "get_session_store",
    "init_redis",
    "close_redis",
    # Cache Strategy
    "CacheStrategy",
    "NoCache",
    "MemoryCache",
    "WriteThrough",
    "WriteBehind",
    "CacheAside",
    "POICacheService",
    "WeatherCacheService",
    "SessionCacheService",
    "LLMCacheService",
    "RouteCacheService",
    "CacheStats",
    "cached",
    "cache_invalidate",
    # Vector Store
    "BaseVectorStore",
    "QdrantStore",
    "InMemoryVectorStore",
    "SearchResult",
    "get_vector_store",
    "init_vector_store",
    "get_store",
    # Vector Service
    "VectorSearchService",
    "POIEmbedding",
    "EmbeddingGenerator",
    "get_vector_service",
    "get_embedding_generator",
    "init_vector_service",
]
